- lib/axe-test-urls.js
- lib/webdriver.js
- package.json
I couldn't run axe-cli at all without these changes–I kept running into Issue #3 and the only way to fix it was to remove the call to `config.driver.quit()` in [lib/webdriver.js](https://github.com/dequelabs/axe-cli/blob/master/lib/webdriver.js#L37). I couldn't find a way to check for a driver session id before making that call, so the solution was to remove it since it threw an error in `.catch(e)` in [axe-test-urls.js:77](https://github.com/dequelabs/axe-cli/blob/master/lib/axe-test-urls.js#L77), even after results had successfully completed:
```
Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:4444
at ClientRequest.<anonymous> (/Users/marcysutton/Sites/Deque/axe-cli/node_modules/selenium-webdriver/http/index.js:238:15)
at emitOne (events.js:96:13)
at ClientRequest.emit …
```
> Fix axe-cli for release

- readme.MD
The example for running specific rules used the an invalid rule "html-lang".
I changed it to "html-has-lang".
*note that when using a wrong rule id, user gets "0 violations found" and is unaware that the rule was not tested.
> Fix "Running specific rules" example

- lib/webdriver.js
- package.json
The initial fix I shipped for https://github.com/dequelabs/axe-cli/issues/3 caused a second problem–by not closing the browser to avoid the error, Webdriver runs leave a browser instance open. I was able to fix that by adding the call back in but wrapping it in a Phantomjs config check. I also updated to axe-core 2.2.0
> Upgrade axe-core and fix webdriver issue

- package.json
When running `axe-cli` in in node version smaller than 6 (this is a least what I tested) it throws the following error:
```
> axe https://www.stefanjudis.de
/Users/stefanjudis/.nvm/versions/node/v5.12.0/lib/node_modules/axe-cli/node_modules/selenium-webdriver/index.js:115
static createSession(...args) {}
^^^
SyntaxError: Unexpected token ...
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:387:25)
at Object.Module._extensions..js (module.js:422:10)
at Module.load (module.js:357:32)
at Function.Module._load (module.js:314:12)
at Module.require (module.js:367:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/Users/stefanjudis/.nvm/versions/node/v5.12.0/lib/node_modules/axe-cli/lib/axe-test-urls.js:3:19)
at Module._compile (module.js:413:34)
at …
```
> fix: add node version restriction

- index.js
- readme.MD
- add `--exit`, `-q` flag
- a11y test `1` exit code behind the flag
- better exit codes for other failures/errors
- readme documentation
closes #20
> Improve Exit Codes

- CONTRIBUTING.md
Manually updating the version is super error-prone, and it already bit me once with axe-cli (I meant to release 1.1.0, yet somehow it got updated to 1.1.1). 
We should use the same process as axe-core for this instead of doing it by hand. Since I'm the one typically releasing our open source modules, I'd really prefer a single process. The only difference with axe-cli is it doesn't use sri-history. I know we're moving to attest-master for Bitbucket repos, but this will give us a workable solution for Github now.
I guess to go along with this change: we should stop incrementing the version by hand until we're ready to release. It's confusing to go hunt it down every time when I'm releasing code.
> Automate release prep with standard-version

- .circleci/config.yml
This helps ensure we're using an up-to-date version of npm.
> ci: use Node.js v10 image

- test/axe-test-urls.js
This patch updates one of our test cases, making it much less brittle. Rather than using whitespace-sensitive string comparison, we're now using a regular expression.
> test: make "ready class" test more forgiving

- .circleci/config.yml
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- index.js
- lib/axe-test-urls.js
- lib/save-outcome.js
- lib/utils.js
- lib/webdriver.js
- package-lock.json
- package.json
- test/axe-test-urls.js
- test/integrations.js
- test/webdriver.js
This patch introduces ESLint and styles all code with Prettier. I've configured Prettier to match the existing code-style as much as possible.
> chore: add ESLint and Prettier

- lib/axe-test-urls.js
- package-lock.json
- package.json
Additionally fix a deprecation warning from `axe-webdriverjs` v2.1.0.
> chore: update `axe-core` and `axe-webdriverjs` deps

- README.md
- index.js
- lib/webdriver.js
This patch adds a `--chrome-options="no-sandbox,disable-setuid-sandbox,..."` flag to the CLI. This flag can be used to provide any custom configuration flag to the Chrome binary.
Closes #65
> feat: add `--chrome-options` flag

- package.json
- test/axe-test-urls.js
- test/integrations.js
- test/webdriver.js
This patch removes an ESLint directive which declared `mocha` as a global variable. Since we never referenced the global, ESLint was erroring with:
```
/home/circleci/axe-cli/test/axe-test-urls.js
1:11  error  'mocha' is defined but never used  no-unused-vars
/home/circleci/axe-cli/test/integrations.js
1:11  error  'mocha' is defined but never used  no-unused-vars
/home/circleci/axe-cli/test/webdriver.js
1:11  error  'mocha' is defined but never used  no-unused-vars
✖ 3 problems (3 errors, 0 warnings)
```
Additionally, the `lint` script now explicitly lists which files it "lints", rather than assuming ESLint is going to do what we want it to.
> chore: fix ESLint errors

- CONTRIBUTING.md
- README.md
> docs: move publishing info to CONTRIBUTING.md

- package.json
We couldn't think of any reason to pin to specific versions of chormedriver, so will now always take the latest version and that should help prevent out of sync issues with chrome. 
> chore: always use latest chromedriver

- .circleci/config.yml
> ci: use `npm ci` to not override package-lock.json

- README.md
- index.js
- lib/webdriver.js
- test/webdriver.js
Add option to CLI to specify the path to the desired ChromeDriver. Allows users to use the specific version of the ChromeDriver that is compatible with their version of Chrome.
```bash
axe dequeuniversity --chromedriver-path "path/to/driver"
```
Closes issue: #103 
> feat: add option `chromedriver-path`

- .circleci/config.yml
- package-lock.json
Our CircleCI npm cache is based on the hash of the package-lock file. However, we run `npm ci` in circle so the package-lock file isn't updated for new installs. This means that using `chromedriver: latest` will never trigger a new install of Chromedriver until we update the package-lock file ourselves and make a push... https://circleci.com/gh/dequelabs/axe-cli/374?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
So I made chromedriver install the latest always for CircleCI.
> chore: update dependencies

- lib/webdriver.js
- test/webdriver.js
Spread the array that was being merged so there are no issues when using the `--chrome-options` flag. This should allow users to pass in `no-sandbox` to work with Linux users. 
> fix: Enable using of --chrome-options argument

- README.md
I fixed the wrong option for verbose output
Closes issue:
> docs: fix '--verbose' option typo

- package.json
BREAKING CHANGE: Drop support for NodeJS 6 and NodeJS 7
Closes issue: #133 
> fix: drop node v6/7 support
